# apiVersion: triggers.tekton.dev/v1beta1
# kind: EventListener
# metadata:
#   name: app-source-listener
#   namespace: tekton-pipelines
# spec:
#   serviceAccountName: tekton-sa
#   resources:
#     kubernetesService:
#       type: ClusterIP
#   triggers:
#     - name: github-push-main
#       interceptors:
#         - ref:
#             name: github
#           params:
#             - name: eventTypes
#               value: ["push"]
#         - ref:
#             name: cel
#           params:
#             - name: filter
#               value: "body.ref == 'refs/heads/main'"
#       bindings:
#         - ref: app-source-binding
#       template:
#         ref: app-source-template

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: app-source-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  # resources:
  #   kubernetesService:
  #     # This is where 'type' (formerly serviceType) lives
  #     spec:
  #       type: ClusterIP
  triggers:
    - name: github-push-main
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["push"]
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: app-source-binding
      template:
        ref: app-source-template