apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: app-event-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa

  triggers:
    - name: github-push-trigger

      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["push"]

        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref.startsWith('refs/heads/main')"

      bindings:
        - ref: app-github-binding

      template:
        ref: app-build-deploy-template